/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ordex/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The observed verification verdict, not the configuration
         * @description Reports configuration completeness and, separately, whether a Bitcoin listing can actually be verified right now: storage writable, both nodes answering, and the ord index within its accepted lag of Bitcoin Core.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/protocol": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The protocol contract this gateway speaks */
        get: operations["getProtocol"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The markets this gateway serves, and what it verifies for each
         * @description Every entry states its verification scope in plain language and its capabilities as booleans. An entry in the catalog never implies a working flow beyond what its capabilities state.
         */
        get: operations["getCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One page of the orderbook
         * @description Paging is keyset, never offset. A request carrying an `offset` parameter is refused with 400, and a malformed cursor is a 400 rather than a silent restart from the first page.
         */
        get: operations["listOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The appended lifecycle log, newest first
         * @description Reads the appended transition log, so an entry is something that happened rather than a listing's current state restated after the fact.
         */
        get: operations["listActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One order */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/orders/{id}/artifact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed artifact for one live listing
         * @description Deliberately its own rate limited request. A browse response carrying raw PSBTs would hand every public ask to anything that can read the market. Only a live listing hands over its artifact; any other state is refused with 400.
         */
        get: operations["getOrderArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/orders/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take a signed artifact and verify it
         * @description A source may supply signed order evidence, but it never overrides what the node and the ord index prove. The claims travel as evidence and the authorities decide the state.
         */
        post: operations["importOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/orders/openordex-event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take a signed OpenOrdex event and verify it
         * @description Accepts a kind 802 Nostr event carrying a signed PSBT, verifies the event signature, then verifies the order exactly as a direct import.
         */
        post: operations["importOpenOrdexEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/orders/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build the unsigned seller half
         * @description Composes the one input, one output PSBT a seller signs `SIGHASH_SINGLE | SIGHASH_ANYONECANPAY`. The asset and outpoint are verified against the node and the ord index before anything is composed.
         */
        post: operations["buildAsk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/orders/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take the signed seller half and publish it */
        post: operations["publishAsk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/orders/{id}/ownership-challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The message a listing owner signs before managing it */
        get: operations["getOwnershipChallenge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/orders/{id}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Remove a listing, proved by the key owning the output it sells
         * @description Withdrawal is discovery, not cancellation. It stops this gateway publishing the listing; it cannot unpublish a signed artifact already distributed elsewhere. Only spending the offered output makes such an artifact unusable.
         */
        post: operations["withdrawOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/admin/orders/{id}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Operator moderation, separately authenticated */
        post: operations["adminWithdrawOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/orders/{id}/nostr-envelope": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The unsigned kind 802 event announcing this listing
         * @description The gateway never holds Nostr keys. The customer's own NIP-07 signer signs this envelope, the browser publishes it, and the signed event can then be handed back through the OpenOrdex import route.
         */
        get: operations["getNostrEnvelope"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/orders/{id}/revalidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recheck one order against both authorities */
        post: operations["revalidateOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/orders/{id}/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compose the buyer half and state the exact terms
         * @description The caller names its own outputs and nothing else. Value and script are read from Bitcoin Core, never from the request, so a buyer cannot make a purchase look cheaper by describing their own funding wrongly. Each named output is checked against the ord index first: an output holding an asset is not spare change, and an unexamined output is unknown rather than empty.
         */
        post: operations["quoteOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/orders/{id}/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify a signed purchase and ask the node whether it would accept it
         * @description Takes either `finalTxHex` or the `signedPsbt` a wallet actually answers with. Given a PSBT it finalises only inputs the buyer already signed: it creates no signature and changes no input, output, or amount, and an unsigned input is an error rather than a guess. It rechecks the order against the chain, binds the transaction to the order, proves the sat flow invariant, then asks the node itself. The gateway does not broadcast; that is the buyer's own deliberate step.
         */
        post: operations["preflightOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/orders/{id}/replace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace a live ask with a freshly signed one for the same output
         * @description Repricing is a protocol operation, not a database edit. The old order must be live, the owner proof must match the offered output, and the new artifact must be signed against the same outpoint. The old order leaves the book as REPLACED and the new one goes live in one step, and two live asks for one output and seller cannot exist.
         */
        post: operations["replaceOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/orders/batch-purchase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compose several live asks into one transaction
         * @description Up to eight asks, one funding plan, one transaction, composed only when every seller signature and every sat flow invariant can coexist. There is no partial composition: when any ask cannot be proved the answer names every refusal and settles nothing.
         */
        post: operations["composeBatchPurchase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/orders/batch-preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify a signed batch and ask the node about the exact bytes
         * @description Rechecks every placement against both authorities, proves the sat flow invariant for every ask, then asks the node whether it would accept the composed transaction. The answer carries the exact bytes checked.
         */
        post: operations["preflightBatchPurchase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One page of the offer book
         * @description Keyset paged exactly like the orders: limit and cursor in, nextCursor out, empty on the last page. A malformed cursor is a 400, never a silent first page.
         */
        get: operations["listOffers"];
        put?: never;
        /**
         * Publish a funded offer
         * @description Takes exact offer terms and funded-output evidence. The gateway recomputes the terms hash, recomputes the Taproot tree and tweak from the two leaves, requires the funded script to commit to both, asks Bitcoin Core whether the output exists and is unspent, and refuses everything else. The offer goes live once the funding confirms.
         */
        post: operations["publishOffer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/offers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One offer with its lifecycle state and freshness */
        get: operations["getOffer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/offers/{id}/revalidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recheck one offer against both authorities */
        post: operations["revalidateOffer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/offers/{id}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Remove an offer from discovery, proved by the recovery key
         * @description Discovery, not cancellation: the funded output stays spendable by the acceptance path until it is spent, and by the recovery path after expiry. A BIP 322 signature by the recovery key proves who may stop publishing the offer.
         */
        post: operations["withdrawOffer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/offers/{id}/acceptance-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * State the exact acceptance arrangement for one live offer
         * @description Given the seller outpoint, reads every value from the node and the ord index, lays out padding, buyer asset, every preserve in sat order, the seller payment at the seller input index, and change, and refuses when the Feline is elsewhere, the root no longer holds, or expiry has passed.
         */
        post: operations["planOfferAcceptance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordex/offers/{id}/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify a built acceptance and ask the node
         * @description Parses the complete acceptance, checks every rule in spec/offers.md including both policy signatures against the committed terms tree, then asks the node whether it would accept the bytes. The answer carries the exact bytes checked.
         */
        post: operations["preflightOfferAcceptance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description An exact non-negative atomic amount as a decimal string. Never floating point, never grouped, never padded. */
        AtomicSats: string;
        /** @enum {string} */
        Network: "mainnet" | "regtest" | "signet";
        /**
         * @description Where order evidence arrived from. Source is provenance, never proof; the node and the ord index decide the state.
         * @enum {string}
         */
        Source: "openordex-nostr802" | "ord-offers" | "direct-import";
        /** @enum {string} */
        OrderClass: "ASK_ANYONECANPAY" | "BID_FULLY_FUNDED" | "UNSUPPORTED";
        /**
         * @description Every state is reachable. A mempool conflict can return to LIVE when the conflicting spend is replaced or dropped; a confirmed spend does not come back short of a reorg. SETTLED is narrower than SPENT: the offered output was spent by a transaction observed carrying this order's exact payout. REPLACED is the terminal state of a live ask whose owner published a fresh ask for the same output through POST /orders/{id}/replace.
         * @enum {string}
         */
        OrderState: "PENDING_NODE" | "PENDING_ORD" | "LIVE" | "MEMPOOL_CONFLICTED" | "SPENT" | "SETTLED" | "REPLACED" | "REJECTED" | "WITHDRAWN";
        /**
         * @description What a customer may do right now. A LIVE order whose verification has aged past its freshness bound is REVIEW_ONLY, not HANDOFF_READY.
         * @enum {string}
         */
        Actionability: "REVIEW_ONLY" | "HANDOFF_READY" | "BLOCKED";
        /** @enum {string} */
        SignatureStatus: "NONE" | "VALID" | "INVALID" | "UNAVAILABLE";
        /** @enum {string} */
        OrderSide: "ASK" | "BID";
        Outpoint: {
            txid: string;
            vout: number;
        };
        AssetClaim: {
            inscriptionId: string;
            outpoint: components["schemas"]["Outpoint"];
            /** @description Read from the local ord index during verification, never from a claim. */
            inscriptionNumber?: number;
        };
        SourceEvidence: {
            source: components["schemas"]["Source"];
            sourceId: string;
            /** Format: date-time */
            observedAt: string;
            eventId?: string;
            eventPubkey?: string;
            signatureVerified?: boolean;
            claimedPriceSats?: components["schemas"]["AtomicSats"];
            claimedAsset?: components["schemas"]["AssetClaim"];
        };
        PsbtInspection: {
            psbtVersion: number;
            unsignedTxid: string;
            digest: string;
            inputCount: number;
            outputCount: number;
            inputOutpoints: components["schemas"]["Outpoint"][];
            inputWitnessUtxos: ({
                scriptHex: string;
                valueSats: components["schemas"]["AtomicSats"];
            } | null)[];
            outputValuesSats: components["schemas"]["AtomicSats"][];
            outputScriptsHex: string[];
            hasProprietaryFields: boolean;
            hasUnknownFields: boolean;
            signatureStatus: components["schemas"]["SignatureStatus"];
            orderClass: components["schemas"]["OrderClass"];
            /** @enum {string} */
            safety: "PUBLIC_RACEABLE" | "TARGETED_REVIEW" | "UNSUPPORTED";
            reasons: string[];
        };
        Validation: {
            /** Format: date-time */
            checkedAt: string;
            /** @enum {string} */
            nodeStatus: "UNCONFIGURED" | "READY" | "UNAVAILABLE" | "OUTPOINT_MISSING" | "OUTPOINT_SPENT";
            /** @enum {string} */
            ordStatus: "NOT_REQUESTED" | "UNCONFIGURED" | "VERIFIED" | "MISMATCH" | "UNAVAILABLE";
            nodeTip?: {
                height: number;
                bestBlockHash: string;
            };
            reasons: string[];
        };
        /** @description Chain settlement the gateway actually observed, never an assumption. */
        Settlement: {
            txid: string;
            /** Format: date-time */
            observedAt: string;
            confirmations: number;
            /** Format: date-time */
            confirmedAt?: string;
        };
        /** @description Read-time freshness of the last verification. Age is published with every order so staleness is visible rather than implied. */
        VerificationView: {
            /** Format: date-time */
            checkedAt: string;
            ageSeconds: number;
            maxAgeSeconds: number;
            stale: boolean;
        };
        Withdrawal: {
            /** Format: date-time */
            withdrawnAt: string;
            reason?: string;
        };
        /** @description What a list or detail response carries. The signed artifact is deliberately absent; it is released only through its own rate limited route while the order is live. */
        OrderSummary: {
            id: string;
            network: components["schemas"]["Network"];
            inspection: components["schemas"]["PsbtInspection"];
            assets: components["schemas"]["AssetClaim"][];
            sources: components["schemas"]["SourceEvidence"][];
            state: components["schemas"]["OrderState"];
            actionability: components["schemas"]["Actionability"];
            validation: components["schemas"]["Validation"];
            /** @description The output script of the PSBT input being sold. Only the key behind it can have created this listing, so it is the identity every seller management action is checked against. */
            sellerScriptHex?: string;
            settlement?: components["schemas"]["Settlement"];
            /** @description User supplied discovery metadata. It never substitutes for chain verification. */
            protocolId?: string;
            token?: string;
            side?: components["schemas"]["OrderSide"];
            quotedPriceSats?: components["schemas"]["AtomicSats"];
            withdrawal?: components["schemas"]["Withdrawal"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        OrderPage: {
            orders: components["schemas"]["OrderSummary"][];
            total: number;
            limit: number;
            /** @description Keyset resume point for the next page. Empty when this page is last. */
            nextCursor: string;
            /** @description Derived from nextCursor, never from a total that concurrent writes can move. */
            hasMore: boolean;
        };
        ActivityEntry: {
            id: string;
            orderId: string;
            /** @description Null for the first transition an order makes. */
            fromState: components["schemas"]["OrderState"] | null;
            toState: components["schemas"]["OrderState"];
            reason: string;
            /** @description Who caused the transition: the reconciler, the seller, an operator, or an import. */
            actor: string;
            /** Format: date-time */
            observedAt: string;
        };
        ActivityPage: {
            entries: components["schemas"]["ActivityEntry"][];
            limit: number;
            nextCursor: string;
            hasMore: boolean;
        };
        OrderArtifact: {
            orderId: string;
            /** @description The signed artifact, base64. */
            psbt: string;
            verification: components["schemas"]["VerificationView"];
            state: components["schemas"]["OrderState"];
            actionability: components["schemas"]["Actionability"];
        };
        ImportRequest: {
            psbt: string;
            source?: components["schemas"]["Source"];
            sourceId?: string;
            asset?: components["schemas"]["AssetClaim"];
            claimedPriceSats?: string | number;
            protocolId?: string;
            token?: string;
            side?: components["schemas"]["OrderSide"];
            quotedPriceSats?: string | number;
        };
        /** @description What a buyer names when asking the gateway to price a purchase. The buyer names its own outputs and nothing else. */
        QuoteRequest: {
            /** @description Where the buyer receives the asset. Never the payment address. */
            assetReceiveAddress?: string;
            /** @description Where the buyer's change and merged padding return. */
            paymentAddress?: string;
            /** @description Outputs placed ahead of the offered one, so the asset reaches the buyer. */
            paddingUtxos?: {
                txid?: string;
                vout?: string | number;
            }[];
            fundingUtxos?: {
                txid?: string;
                vout?: string | number;
            }[];
            feeRateSatsPerVb?: string | number;
        };
        /** @description Everything a buyer needs to decide, and the unsigned half their wallet will be asked to sign. Every amount is atomic sats as a string. */
        Quote: {
            orderId: string;
            network: components["schemas"]["Network"];
            psbt: string;
            /** @description The index the seller's input and payment output share. */
            sellerIndex: number;
            asset: components["schemas"]["AssetClaim"] | null;
            assetReceiveAddress: string;
            paymentAddress: string;
            sellerPaymentScriptHex: string;
            assetValueSats: components["schemas"]["AtomicSats"];
            sellerProceedsSats: components["schemas"]["AtomicSats"];
            marketplaceFeeSats: components["schemas"]["AtomicSats"];
            creatorRoyaltySats: components["schemas"]["AtomicSats"];
            networkFeeSats: components["schemas"]["AtomicSats"];
            feeRateSatsPerVb: string;
            estimatedVbytes: string;
            changeSats: components["schemas"]["AtomicSats"];
            /** @description Padding the buyer supplies and receives back, so it is not a cost. */
            paddingSats: components["schemas"]["AtomicSats"];
            totalBuyerCostSats: components["schemas"]["AtomicSats"];
            inputOutpoints: components["schemas"]["Outpoint"][];
            outputScriptsHex: string[];
            outputValuesSats: components["schemas"]["AtomicSats"][];
            checkpoint: {
                heightAtomic: components["schemas"]["AtomicSats"];
                blockHash: string;
            };
            /** Format: date-time */
            observedAt: string;
            /** Format: date-time */
            expiresAt: string;
        };
        /** @description Either the final transaction hex or the signed PSBT a wallet actually answers with. */
        PreflightRequest: {
            finalTxHex?: string;
            signedPsbt?: string;
        };
        PreflightResult: {
            /** @description The exact bytes checked, so a buyer broadcasts those and no others. */
            finalTxHex?: string;
            orderId: string;
            allowed: boolean;
            rejectReason?: string;
            txid?: string;
            vsize?: number;
            feesSats?: components["schemas"]["AtomicSats"];
            /** Format: date-time */
            checkedAt: string;
        };
        BuildAskRequest: {
            protocolId: string;
            token: string;
            quotedPriceSats: string | number;
            sellerPaymentAddress: string;
            asset?: components["schemas"]["AssetClaim"];
            outpoint?: components["schemas"]["Outpoint"];
        };
        BuildAskResult: {
            psbt: string;
            inspection: components["schemas"]["PsbtInspection"];
            outpoint: components["schemas"]["Outpoint"];
            nodeTip: {
                height: number;
                bestBlockHash: string;
            };
            protocolId: string;
            /** @enum {string} */
            builderProfile: "OPEN_ASK" | "EXTERNAL_PSBT" | "EXTERNAL_SETTLEMENT";
        };
        PublishAskRequest: {
            /** @description The seller half, now signed by the seller's own wallet. */
            psbt: string;
        } & components["schemas"]["BuildAskRequest"];
        /** @description The message a seller signs to prove they own a listing's source UTXO. */
        OwnershipChallenge: {
            orderId: string;
            address: string;
            message: string;
            /** Format: date-time */
            windowStart: string;
            /** Format: date-time */
            expiresAt: string;
        };
        OwnershipProof: {
            address?: string;
            signature?: string;
            reason?: string;
        };
        NostrEnvelope: {
            /** @constant */
            kind: 802;
            created_at: number;
            tags: string[][];
            content: string;
            notice: string;
        };
        NostrEvent: {
            id: string;
            pubkey: string;
            created_at: number;
            kind: number;
            tags: string[][];
            content: string;
            sig: string;
        };
        /** @description What a protocol can truthfully do today. An entry in the catalog never implies a working flow beyond these booleans. */
        ProtocolCapabilities: {
            browse: boolean;
            createListing: boolean;
            /** @description True when the local ord index proves the asset's current location, not only that its UTXO is unspent. */
            verifyAssetSemantics: boolean;
            reviewOnlyHandoff: boolean;
            externalSettlement: boolean;
            sourceIngestion: boolean;
            mediaResolution: boolean;
        };
        ProtocolTemplate: {
            id: string;
            label: string;
            route: string;
            /** @enum {string} */
            family: "bitcoin" | "dogecoin" | "counterparty";
            /** @enum {string} */
            capability: "PSBT_HANDOFF" | "EXTERNAL_SETTLEMENT";
            /** @enum {string} */
            builderProfile: "OPEN_ASK" | "EXTERNAL_PSBT" | "EXTERNAL_SETTLEMENT";
            /** @enum {string} */
            assetRequirement: "INSCRIPTION" | "OUTPOINT" | "NONE";
            templateLabel: string;
            templateGuidance: string;
            /** @description Plain language scope of what verification proves for this protocol. Never softened to look more capable. */
            verificationScope: string;
            capabilities: components["schemas"]["ProtocolCapabilities"];
            groupId: string;
            groupLabel: string;
            groupOrder: number;
            displayOrder: number;
            /** @description Set when this id is a catalog alias of another protocol. Aliases stay filterable but are not offered as a separate market leaf. */
            aliasOf?: string;
        };
        /** @description Whether a Bitcoin listing can actually be verified right now. Observed, never inferred from the presence of a URL. */
        ListingReadiness: {
            ready: boolean;
            reason: ("not_configured" | "storage_unavailable" | "core_unavailable_or_syncing" | "ord_unreachable" | "ord_index_behind" | "observation_timed_out") | null;
            coreHeight: number | null;
            ordHeight: number | null;
            lagBlocks: number | null;
            maxLagBlocks: number;
            storageWritable: boolean;
            /** Format: date-time */
            checkedAt: string;
        };
        HealthReport: {
            ok: boolean;
            /** @constant */
            service: "ordex";
            enabled: boolean;
            defaultEnabled: boolean;
            network: components["schemas"]["Network"];
            /** @enum {string} */
            status: "active" | "degraded" | "disabled";
            /** @constant */
            featureFlag: "ORDEX_ENABLED";
            coreConfigured: boolean;
            ordConfigured: boolean;
            configurationComplete: boolean;
            /** @constant */
            signsOrBroadcasts: false;
            /** @constant */
            spendsFunds: false;
            supportedSources: components["schemas"]["Source"][];
            storageWritable: boolean;
            readyForBitcoinListings: boolean;
            maxVerificationAgeSeconds: number;
            listingReadiness: components["schemas"]["ListingReadiness"];
        };
        ProtocolContract: {
            /** @constant */
            name: "Ordex";
            settlement: string;
            sourceOfTruth: string;
            supportedProfiles: string[];
            orderTemplates: {
                supportedProtocols: number;
                supportedGroups: number;
                psbtHandoff: string;
            };
            safety: {
                publicAsk: string;
                /** @constant */
                combinesPsbt: false;
                /** @constant */
                signsOrBroadcasts: false;
            };
            nostr: {
                /** @constant */
                ingestion: "publish-only";
                note: string;
            };
        };
        /**
         * @description What an offer binds to. ITEM names one exact inscription; COLLECTION names every Feline included in the committed root; TRAIT names one exact trait name and value inside that root.
         * @enum {string}
         */
        OfferKind: "ITEM" | "COLLECTION" | "TRAIT";
        /**
         * @description The funded-output lifecycle. PENDING_CONFIRMATION is not live. ACCEPTED and RECOVERED are the two settled outcomes. EXPIRED means the current height passed expiryHeight with the output unspent, so recovery is the only remaining path. WITHDRAWN is discovery, not cancellation: only a spend settles the funds.
         * @enum {string}
         */
        OfferState: "PENDING_CONFIRMATION" | "LIVE" | "ACCEPTED" | "RECOVERED" | "MEMPOOL_CONFLICTED" | "SPENT" | "EXPIRED" | "WITHDRAWN" | "REJECTED";
        OfferTerms: {
            /**
             * @description The terms schema this contract carries.
             * @constant
             */
            schema: "ordex.offer-terms/v1";
            /** @description The gateway protocol version the terms were written for, 1.1 or later. */
            protocolVersion: string;
            network: components["schemas"]["Network"];
            offerKind: components["schemas"]["OfferKind"];
            /** @description The collection the scope names. */
            collectionId: string;
            /** @description Lowercase hex SHA-256 collection Merkle root the scope binds to. */
            collectionRoot: string;
            /** @description ITEM offers only: the exact inscription the offer buys. */
            itemInscriptionId?: string;
            /** @description TRAIT offers only: the exact trait name. */
            traitName?: string;
            /** @description TRAIT offers only: the exact trait value. */
            traitValue?: string;
            /** @description SHA-256 over the exact serialized scope criteria the buyer accepted, so a verifier can recheck scope membership without trusting a description of it. */
            criteriaHash: string;
            /** @description Lowercase hex script the bought Feline must land in. */
            buyerReceiveScriptHex: string;
            /** @description Exact price paid to the accepting seller. */
            priceSats: components["schemas"]["AtomicSats"];
            /** @description The largest fee an acceptance may pay. */
            maxNetworkFeeSats: components["schemas"]["AtomicSats"];
            /** @description Block height after which acceptance is refused and the recovery path unlocks. */
            expiryHeight: number;
            /** @description Lowercase hex x-only key that can recover the funded output alone after expiry. */
            buyerRecoveryKeyHex: string;
        };
        /** @description SHA-256 over the terms serialized as UTF-8 JSON with object keys sorted recursively and no insignificant whitespace. Two parties that hold the same terms hold the same hash. */
        OfferTermsHash: string;
        OfferFunding: {
            /** @description The transaction that created the funded output. */
            fundedTxid: string;
            /** @description The funded output index. */
            fundedVout: number;
            /** @description Lowercase hex x-only internal key of the funded output. */
            tapInternalKeyHex: string;
            /** @description The acceptance leaf: the terms hash push, both policy keys, CHECKSIG, CHECKSIGADD, and the 2-of-2 equal. The gateway recomputes the tree and the tweak from these leaves, so the funded script must commit to the exact terms. */
            acceptanceLeafScriptHex: string;
            /** @description The recovery leaf: the expiry height, CHECKLOCKTIMEVERIFY, and the buyer recovery key. */
            recoveryLeafScriptHex: string;
        };
        OfferValidation: {
            /**
             * Format: date-time
             * @description When both authorities were last asked.
             */
            checkedAt: string;
            /**
             * @description What Bitcoin Core said about the funded output.
             * @enum {string}
             */
            nodeStatus: "UNCONFIGURED" | "READY" | "UNAVAILABLE" | "OUTPOINT_MISSING" | "OUTPOINT_SPENT";
            /**
             * @description What the collection authority said about the committed root.
             * @enum {string}
             */
            rootStatus: "NOT_REQUESTED" | "UNCONFIGURED" | "VERIFIED" | "ROOT_MISMATCH" | "UNAVAILABLE";
        };
        OfferSummary: {
            /** @description The gateway identifier for this offer. */
            id: string;
            terms: components["schemas"]["OfferTerms"];
            offerTermsHash: components["schemas"]["OfferTermsHash"];
            funding: components["schemas"]["OfferFunding"];
            state: components["schemas"]["OfferState"];
            actionability?: components["schemas"]["Actionability"];
            validation: components["schemas"]["OfferValidation"];
            /** @description ACCEPTED and RECOVERED offers only: the transaction that settled the funds. */
            settledByTxid?: string;
            /** @description ACCEPTED offers only: the order whose acceptance carried the settlement. */
            acceptedOrderId?: string;
            /**
             * Format: date-time
             * @description When the gateway published the offer.
             */
            postedAt: string;
            checkpoint?: components["schemas"]["ListingReadiness"];
        };
        OfferPage: {
            offers: components["schemas"]["OfferSummary"][];
            /** @description Empty on the last page. Resume from here for a stable, offset-free read. */
            nextCursor?: string;
            hasMore: boolean;
        };
        OfferPublishRequest: {
            terms: components["schemas"]["OfferTerms"];
            funding: components["schemas"]["OfferFunding"];
        };
        OfferAcceptancePlanRequest: {
            /** @description The output the accepting seller will spend to deliver the Feline. */
            sellerFelineOutpoint: components["schemas"]["Outpoint"];
            /** @description The script the seller payment output must carry, committed by the seller signature. */
            sellerPaymentScriptHex: string;
        };
        OfferAcceptancePlan: {
            /** @description The offer this plan settles. */
            offerId: string;
            /** @description Where the Feline input sits, and with it the seller payment. */
            sellerInputIndex: number;
            /** @description Where the funded offer output sits. */
            offerInputIndex: number;
            sellerPaymentOutputIndex: number;
            buyerAssetOutputIndex: number;
            /** @description Every input in transaction order, with the exact values read from the node. */
            inputs: {
                txid: string;
                vout: number;
                valueSats: components["schemas"]["AtomicSats"];
                /** @enum {string} */
                role: "PADDING" | "OFFER" | "SELLER_FELINE";
            }[];
            /** @description Every output in transaction order: padding merge, buyer asset, seller preserves in sat order, seller payment at the seller input index, buyer change last. */
            outputs: {
                scriptHex: string;
                valueSats: components["schemas"]["AtomicSats"];
                /** @enum {string} */
                role: "PADDING_MERGE" | "BUYER_ASSET" | "SELLER_PRESERVE" | "SELLER_PAYMENT" | "BUYER_CHANGE";
            }[];
            /** @description The fee the composed arrangement pays at the current rate. */
            estimatedFeeSats: components["schemas"]["AtomicSats"];
            /** @description False means the terms refuse acceptance as composed. */
            withinMaxNetworkFee: boolean;
            /** @description The terms expiry height, restated so a stale plan is visible. */
            expiresAtHeight: number;
            checkpoint: components["schemas"]["ListingReadiness"];
        };
        OfferPreflightRequest: {
            /** @description The complete acceptance, seller signature and both policy signatures included. */
            finalTxHex: string;
        };
        OfferPreflightResult: {
            offerId: string;
            allowed: boolean;
            /** @description Present when not allowed. */
            rejectReason?: string;
            /** @description The exact bytes checked, so a seller broadcasts those and no others. */
            finalTxHex?: string;
            txid?: string;
            vsize?: number;
            feesSats?: components["schemas"]["AtomicSats"];
            /** @description How many of the two acceptance-leaf signatures the parsed witness carries. */
            policySignatureCount?: number;
            /** @description What the node answered when asked whether it would accept these bytes. */
            nodeAcceptance?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            checkedAt: string;
        };
        /** @description A freshly signed seller half for the same offered output, plus the same owner proof withdrawal requires. The old order leaves the book as REPLACED and the new one goes live in one step. */
        ReplaceAskRequest: {
            artifact: components["schemas"]["PublishAskRequest"];
            ownership: components["schemas"]["OwnershipProof"];
        };
        ReplaceAskResult: {
            /** @description The order this replacement retired. */
            replacedOrderId: string;
            order: components["schemas"]["OrderSummary"];
        };
        BatchPurchaseRequest: {
            /** @description The live asks to settle in one transaction, in the order the buyer reviewed them. */
            orderIds: string[];
            /** @description Where every purchased Feline lands, one output per ask. */
            assetReceiveAddress: string;
            /** @description Where padding merges and change return to the buyer. */
            paymentAddress: string;
            /** @description Two asset-free cardinal outputs per ask, read back from the node before anything is composed. */
            paddingUtxos: components["schemas"]["Outpoint"][];
            /** @description Cardinal outputs that cover every price and the fee. */
            fundingUtxos: components["schemas"]["Outpoint"][];
            /** @description The exact rate the buyer approved. */
            feeRateSatsPerVb: number;
        };
        BatchPurchaseResult: {
            /** @description The unsigned buyer half. Every seller input arrives already signed; the buyer signs only their own inputs. */
            psbt: string;
            placements: {
                orderId: string;
                sellerInputIndex: number;
                sellerPaymentOutputIndex: number;
                buyerAssetOutputIndex: number;
                /** @description This ask's exact price. */
                priceSats?: components["schemas"]["AtomicSats"];
            }[];
            totals: {
                /** @description Every price, every fee, and every padding sat, stated once. */
                totalBuyerCostSats: components["schemas"]["AtomicSats"];
                networkFeeSats: components["schemas"]["AtomicSats"];
            };
            /**
             * Format: date-time
             * @description How long the composed batch stays composable before at least one ask can no longer be proved.
             */
            expiresAt: string;
        };
        BatchRefusal: {
            /** @description The refused ask. */
            orderId: string;
            /** @description A stable, machine readable refusal code. */
            code: string;
            /** @description A human explanation of the same refusal. */
            reason: string;
        };
        /** @description Answered when at least one ask cannot coexist in the batch. There is no partial composition: every refused order is named, and the client falls back to separate purchases. */
        BatchPurchaseRefused: {
            refusals: components["schemas"]["BatchRefusal"][];
        };
        BatchPreflightRequest: {
            /** @description The identifier the batch-purchase answer carried. */
            batchId: string;
            /** @description The batch PSBT with every buyer input signed. */
            signedPsbt?: string;
            /** @description Or the exact final bytes, when already finalized. */
            finalTxHex?: string;
        };
        BatchPreflightResult: {
            allowed: boolean;
            /** @description The exact bytes checked, so a buyer broadcasts those and no others. */
            finalTxHex?: string;
            txid?: string;
            vsize?: number;
            feesSats?: components["schemas"]["AtomicSats"];
            placements: {
                orderId: string;
                allowed: boolean;
                /** @description Present when this ask failed inside an otherwise parseable batch. */
                rejectReason?: string;
            }[];
            /** @description What the node answered about the exact composed bytes. */
            nodeAcceptance?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            checkedAt: string;
        };
        /** @description The error envelope every route answers with. Rate limited requests additionally carry `code: ORDEX_RATE_LIMITED`. */
        ErrorResponse: {
            statusCode: number;
            error: string;
            message: string | string[];
            requestId?: string;
            code?: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description The request failed. The envelope states the status, a human readable message, and the request id. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request is malformed or refused, with the exact reason in `message`. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description No order with this id. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limited. The envelope carries `code: ORDEX_RATE_LIMITED`. */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description The order id. */
        OrderId: string;
        /** @description The gateway offer identifier. */
        OfferId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The health report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getProtocol: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The protocol contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProtocolContract"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The protocol catalog. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProtocolTemplate"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listOrders: {
        parameters: {
            query?: {
                /** @description One catalog protocol id. */
                protocol?: string;
                /** @description Comma separated catalog ids. Applied before sorting and pagination. */
                protocols?: string;
                /** @description A catalog group id, expanded to every protocol it contains. */
                group?: string;
                token?: string;
                source?: components["schemas"]["Source"];
                /** @description An order state from `OrderState`. */
                state?: string;
                /** @description A safety class from `PsbtInspection.safety`. */
                safety?: string;
                orderClass?: string;
                /** @description A signature status from `SignatureStatus`. */
                signature?: string;
                side?: string;
                /** @description Restricts the page to the listings one seller script owns. */
                seller?: string;
                /** @description Restricts the page to orders claiming one inscription. Resolved through an index of order claims. */
                assetInscriptionId?: string;
                /** @description Restricts the page to orders claiming an asset at one `txid:vout`. */
                assetOutpoint?: string;
                search?: string;
                /** @description Every sort ends on the order id, which is unique, so the ordering is total and a cursor resumes exactly. An unpriced order sorts after every priced one in both price directions. */
                sort?: "newest" | "oldest" | "price_asc" | "price_desc" | "token_asc" | "protocol_asc" | "validation_newest";
                includeWithdrawn?: string;
                /** @description Page size as a decimal string. */
                limit?: string;
                /** @description The keyset resume point a previous page answered with. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of orders. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            default: components["responses"]["Error"];
        };
    };
    listActivity: {
        parameters: {
            query?: {
                orderId?: string;
                limit?: string;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of lifecycle transitions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order id. */
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The order, without its signed artifact. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummary"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    getOrderArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order id. */
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed artifact and its current verification. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderArtifact"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            default: components["responses"]["Error"];
        };
    };
    importOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description The imported order after verification. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
            default: components["responses"]["Error"];
        };
    };
    importOpenOrdexEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NostrEvent"];
            };
        };
        responses: {
            /** @description The imported order after verification. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
            default: components["responses"]["Error"];
        };
    };
    buildAsk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildAskRequest"];
            };
        };
        responses: {
            /** @description The unsigned seller half and its inspection. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildAskResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
            default: components["responses"]["Error"];
        };
    };
    publishAsk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishAskRequest"];
            };
        };
        responses: {
            /** @description The published order after verification. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
            default: components["responses"]["Error"];
        };
    };
    getOwnershipChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order id. */
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The challenge to sign with the key that owns the offered output. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnershipChallenge"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    withdrawOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order id. */
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnershipProof"];
            };
        };
        responses: {
            /** @description The withdrawn order. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            default: components["responses"]["Error"];
        };
    };
    adminWithdrawOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order id. */
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description The withdrawn order. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummary"];
                };
            };
            /** @description Operator credentials missing, invalid, or not configured. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    getNostrEnvelope: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order id. */
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The unsigned event envelope. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NostrEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    revalidateOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order id. */
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The order after a fresh verification. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummary"];
                };
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            default: components["responses"]["Error"];
        };
    };
    quoteOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order id. */
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteRequest"];
            };
        };
        responses: {
            /** @description The unsigned buyer half and the exact economics. A fee or a royalty of zero is stated as zero rather than omitted. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quote"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            default: components["responses"]["Error"];
        };
    };
    preflightOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order id. */
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreflightRequest"];
            };
        };
        responses: {
            /** @description The verdict, with the exact bytes checked so a buyer broadcasts those and no others. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreflightResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            default: components["responses"]["Error"];
        };
    };
    replaceOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order id. */
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceAskRequest"];
            };
        };
        responses: {
            /** @description The retired order id and the live replacement. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplaceAskResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            default: components["responses"]["Error"];
        };
    };
    composeBatchPurchase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchPurchaseRequest"];
            };
        };
        responses: {
            /** @description The composed batch with every placement stated. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchPurchaseResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description At least one ask cannot coexist in the batch. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchPurchaseRefused"];
                };
            };
            429: components["responses"]["RateLimited"];
            default: components["responses"]["Error"];
        };
    };
    preflightBatchPurchase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchPreflightRequest"];
            };
        };
        responses: {
            /** @description The per-ask verdicts and the node answer. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchPreflightResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            default: components["responses"]["Error"];
        };
    };
    listOffers: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
                offerKind?: components["schemas"]["OfferKind"];
                collectionId?: string;
                state?: components["schemas"]["OfferState"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The offer page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
            default: components["responses"]["Error"];
        };
    };
    publishOffer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferPublishRequest"];
            };
        };
        responses: {
            /** @description The published offer in PENDING_CONFIRMATION. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            default: components["responses"]["Error"];
        };
    };
    getOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The gateway offer identifier. */
                id: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The offer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            default: components["responses"]["Error"];
        };
    };
    revalidateOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The gateway offer identifier. */
                id: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The rechecked offer. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            default: components["responses"]["Error"];
        };
    };
    withdrawOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The gateway offer identifier. */
                id: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnershipProof"];
            };
        };
        responses: {
            /** @description The withdrawn offer. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            default: components["responses"]["Error"];
        };
    };
    planOfferAcceptance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The gateway offer identifier. */
                id: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferAcceptancePlanRequest"];
            };
        };
        responses: {
            /** @description The exact arrangement to build and sign. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferAcceptancePlan"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            default: components["responses"]["Error"];
        };
    };
    preflightOfferAcceptance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The gateway offer identifier. */
                id: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferPreflightRequest"];
            };
        };
        responses: {
            /** @description The acceptance verdict. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferPreflightResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            default: components["responses"]["Error"];
        };
    };
}
